defaults:
  - _self_
  - feature_extractor: null

wandb_project: "APMTH-Project"

# Environment
env_name: "l2rpn_case14_sandbox"

# Algorithm: "ppo" or "sac"
algo: "sac"
mlp_layers: [128, 128]

# Training configuration
total_timesteps: 250_000
checkpoint_freq: 50_000
eval_freq: 50_000

# Evaluation configuration
train_envs: 5
n_eval: 10


