defaults:
  - _self_
  - feature_extractor: ~ 

wandb_project: "APMTH-Project"

# Environment
env_name: "l2rpn_case14_sandbox_train-v0"
eval_env_name: "l2rpn_case14_sandbox_val-v0"

# Algorithm: "ppo" or "sac"
algo: "sac"
mlp_layers: [128, 128]

# Training configuration
total_timesteps: 1_000_000
checkpoint_freq: 10_000
eval_freq: 10_000

# Evaluation configuration
train_envs: 5
n_eval: 10
eval_envs: 10


